name: meta_seo_module
description: "Meta SEO module for juneflow project."
#publish_to: 'none'
repository: https://github.com/juneflow-songdo/meta_seo_module

version: 1.0.2

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  go_router:
  june_flow_util:
  meta_seo:  #@add

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/module/meta_seo_module/
  uses-material-design: true