name: meta_seo_module
description: "Description here"
#publish_to: 'none'
#repository: https://github.com/melodysdreamj/juneflow

version: 0.0.1+1

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  go_router: ^13.2.2
  june_flow_util: ^0.8.19
  meta_seo: ^3.0.9 #@add

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/module/meta_seo_module/
  uses-material-design: true